#!/usr/bin/env node

/**
 * UniHUB Setup Assistant
 * Helps configure the database connection
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const envFile = path.join(__dirname, '.env');
const envExampleFile = path.join(__dirname, '.env.example');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const question = (prompt) => {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
};

async function setup() {
  console.log('\n🎓 UniHUB - PostgreSQL Database Setup Assistant\n');
  console.log('This tool will help you configure your database connection.\n');

  // Check if .env already exists
  if (fs.existsSync(envFile)) {
    const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/n): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n✅ Setup cancelled. Your existing .env file is unchanged.');
      rl.close();
      return;
    }
  }

  console.log('\nPlease enter your PostgreSQL credentials:\n');

  const dbUser = await question('📝 Database User (default: postgres): ') || 'postgres';
  const dbPassword = await question('🔐 Database Password: ');
  const dbHost = await question('🖥️  Database Host (default: localhost): ') || 'localhost';
  const dbPort = await question('⚙️  Database Port (default: 5432): ') || '5432';
  const dbName = await question('📚 Database Name (default: unihub): ') || 'unihub';
  const port = await question('🚀 Server Port (default: 5000): ') || '5000';

  // Validate inputs
  if (!dbPassword) {
    console.log('\n❌ Database password is required!');
    rl.close();
    return;
  }

  // Create .env file
  const envContent = `# UniHUB Database Configuration
# Generated by setup assistant - $(date)

# Database Configuration
DB_USER=${dbUser}
DB_PASSWORD=${dbPassword}
DB_HOST=${dbHost}
DB_PORT=${dbPort}
DB_NAME=${dbName}

# Server Configuration
PORT=${port}
NODE_ENV=development

# API Settings
API_TIMEOUT=5000
CACHE_TIMEOUT=300000
`;

  try {
    fs.writeFileSync(envFile, envContent);
    console.log('\n✅ Configuration saved to .env\n');
    console.log('📋 Configuration Summary:');
    console.log(`   Database: ${dbName} on ${dbHost}:${dbPort}`);
    console.log(`   User: ${dbUser}`);
    console.log(`   Server: http://localhost:${port}\n`);

    console.log('🚀 Next steps:');
    console.log('   1. Ensure PostgreSQL is running');
    console.log('   2. Create database tables (see DATABASE_SETUP.md)');
    console.log('   3. Run: npm start\n');

    console.log('📖 For more information, see:');
    console.log('   - QUICKSTART.md');
    console.log('   - DATABASE_SETUP.md\n');
  } catch (error) {
    console.error('\n❌ Error writing .env file:', error);
  }

  rl.close();
}

setup();
